const GLOBAL = {
  server: 'https://localhost:8000',
  themes: [
    { name: 'Visual Studio', value: 'vs' },
    { name: 'Visual Studio Dark', value: 'vs-dark' },
    { name: 'High Contrast Dark', value: 'hc-black' }
  ],
  languages: [
    { name: '', value: 'abap' },
    { name: '', value: 'apex' },
    { name: '', value: 'azcli' },
    { name: '', value: 'cameligo' },
    { name: '', value: 'clojure' },
    { name: '', value: 'clojure' },
    { name: '', value: 'coffee' },
    { name: '', value: 'coffee' },
    { name: '', value: 'cpp' },
    { name: '', value: 'csharp' },
    { name: '', value: 'csp' },
    { name: '', value: 'css' },
    { name: '', value: 'dockerfile' },
    { name: '', value: 'fsharp' },
    { name: '', value: 'go' },
    { name: '', value: 'graphql' },
    { name: '', value: 'handlebars' },
    { name: '', value: 'html' },
    { name: '', value: 'ini' },
    { name: '', value: 'java' },
    { name: '', value: 'javascript' },
    { name: '', value: 'json' },
    { name: '', value: 'kotlin' },
    { name: '', value: 'less' },
    { name: '', value: 'lua' },
    { name: '', value: 'markdown' },
    { name: '', value: 'mips' },
    { name: '', value: 'msdax' },
    { name: '', value: 'mysql' },
    { name: '', value: 'objective-c' },
    { name: '', value: 'pascal' },
    { name: '', value: 'pascaligo' },
    { name: '', value: 'perl' },
    { name: '', value: 'pgsql' },
    { name: '', value: 'php' },
    { name: '', value: 'postiats' },
    { name: '', value: 'powerquery' },
    { name: '', value: 'powershell' },
    { name: '', value: 'pug' },
    { name: '', value: 'r' },
    { name: '', value: 'razor' },
    { name: '', value: 'redis' },
    { name: '', value: 'redshift' },
    { name: '', value: 'restructuredtext' },
    { name: '', value: 'ruby' },
    { name: '', value: 'rust' },
    { name: '', value: 'sb' },
    { name: '', value: 'scheme' },
    { name: '', value: 'scss' },
    { name: '', value: 'shell' },
    { name: '', value: 'solidity' },
    { name: '', value: 'sophia' },
    { name: '', value: 'sql' },
    { name: '', value: 'st' },
    { name: '', value: 'swift' },
    { name: '', value: 'tcl' },
    { name: '', value: 'twig' },
    { name: '', value: 'typescript' },
    { name: '', value: 'vb' },
    { name: '', value: 'xml' },
    { name: '', value: 'yaml' }
  ]
}

export default GLOBAL;