const GLOBAL = {
  server: 'http://localhost:8000',
  themes: [
    { name: 'Visual Studio', value: 'vs' },
    { name: 'Visual Studio Dark', value: 'vs-dark' },
    { name: 'High Contrast Dark', value: 'hc-black' }
  ],
  languages: [
    { name: 'abap', value: 'abap' },
    { name: 'apex', value: 'apex' },
    { name: 'azcli', value: 'azcli' },
    { name: 'bat', value: 'bat' },
    { name: 'cameligo', value: 'cameligo' },
    { name: 'clojure', value: 'clojure' },
    { name: 'coffee', value: 'coffee' },
    { name: 'cpp', value: 'cpp' },
    { name: 'csharp', value: 'csharp' },
    { name: 'csp', value: 'csp' },
    { name: 'css', value: 'css' },
    { name: 'dockerfile', value: 'dockerfile' },
    { name: 'fsharp', value: 'fsharp' },
    { name: 'go', value: 'go' },
    { name: 'graphql', value: 'graphql' },
    { name: 'handlebars', value: 'handlebars' },
    { name: 'html', value: 'html' },
    { name: 'ini', value: 'ini' },
    { name: 'java', value: 'java' },
    { name: 'javascript', value: 'javascript' },
    { name: 'json', value: 'json' },
    { name: 'kotlin', value: 'kotlin' },
    { name: 'less', value: 'less' },
    { name: 'lua', value: 'lua' },
    { name: 'markdown', value: 'markdown' },
    { name: 'mips', value: 'mips' },
    { name: 'msdax', value: 'msdax' },
    { name: 'mysql', value: 'mysql' },
    { name: 'objective-c', value: 'objective-c' },
    { name: 'pascal', value: 'pascal' },
    { name: 'pascaligo', value: 'pascaligo' },
    { name: 'perl', value: 'perl' },
    { name: 'pgsql', value: 'pgsql' },
    { name: 'php', value: 'php' },
    { name: 'postiats', value: 'postiats' },
    { name: 'powerquery', value: 'powerquery' },
    { name: 'powershell', value: 'powershell' },
    { name: 'pug', value: 'pug' },
    { name: 'python', value: 'python' },
    { name: 'r', value: 'r' },
    { name: 'razor', value: 'razor' },
    { name: 'redis', value: 'redis' },
    { name: 'redshift', value: 'redshift' },
    { name: 'restructuredtext', value: 'restructuredtext' },
    { name: 'ruby', value: 'ruby' },
    { name: 'rust', value: 'rust' },
    { name: 'sb', value: 'sb' },
    { name: 'scheme', value: 'scheme' },
    { name: 'scss', value: 'scss' },
    { name: 'shell', value: 'shell' },
    { name: 'solidity', value: 'solidity' },
    { name: 'sophia', value: 'sophia' },
    { name: 'sql', value: 'sql' },
    { name: 'st', value: 'st' },
    { name: 'swift', value: 'swift' },
    { name: 'tcl', value: 'tcl' },
    { name: 'twig', value: 'twig' },
    { name: 'typescript', value: 'typescript' },
    { name: 'vb', value: 'vb' },
    { name: 'xml', value: 'xml' },
    { name: 'yaml', value: 'yaml' }
  ]
}

export default GLOBAL;